### ISSUE TITLE
Combine with my module?

### ISSUE THREAD

**Issue by brettimus** [ksivamuthu/quill-html-placeholder#1]
Hey there-  I saw this is essentially a fork of my `quill-placeholder` module. Would you like to combine the two and be co-collaborators?

I also have some thoughts on how to improve the module if you want to talk about that.

**Comment by ksivamuthu** [comment]
@brettimus Yes I wish to. I would like to collaborator on your module.

**Comment by brettimus** [comment]
Well i just rewrote the module on the [v1 branch of my repo](https://github.com/brettimus/quill-placeholder/tree/v1) to allow text or html. (also i refrained from adding text directly to the editor, which solves the form validation pains)

if you find bugs or have specific features you'd like to to contribute, i'll add you!

also, in the future, it'd be nice to have some attribution on my work :wink: (though you are in no way obliged)
